### ISSUE TITLE
Add support for iterator

### ISSUE THREAD

**Issue by bandophahita** [typed-argparse/typed-argparse#12]
The `TypedArgs` object doesn't allow for writing the following:
```python
args = MyNamespace(parser.parse_args())
if 'custom_attrib' in args:
    ...
```
The above results in `TypeError: argument of type 'MyNamespace' is not iterable`

**Comment by bluenote10** [comment]
Anything dynamic like `'custom_attrib' in args` goes a bit against the idea of having an typed argument class, right? Perhaps you can elaborate what you are trying to achieve?

Note that you can always access the underlying raw `argparse.Namespace` object if needed.

**Comment by bluenote10** [comment]
I'd close this assuming the issue has been resolved? Feel free to re-open / ask more if needed.
