### ISSUE TITLE
Feature - Inverted bool flags/switches

### ISSUE THREAD

**Issue by ptous** [typed-argparse/typed-argparse#38]
First, thanks for this. I really find it useful and (having peered at it a bit) really like the implementation too.

To the point though, I wonder what you would think of an API -based way of inverting the meaning of Boolean switches without requiring the inversion of the meaning of the variable/arg itself.

To hopefully be more clear, here's an templatized example from my existing `argparse` code.

```
    parser.add_argument(
        "--no-blah",
        action="store_false",
        default=True,
        dest="blah",
        help="..."
    )
```

This is written this way because the default behavior for the code behind `args.blah` to run, and disabling it is an unusual (but sometimes useful) case.

I realize that this behavior is already supported by simply inverting the name of the Arg. Calling it `no_blah` while setting the default value to `False` achieves the same result.

However, I like being able to invert the switch's meaning in the `ArgumentParser` setup because referring to the inverted arg becomes a bit perverse in the application logic (at least in my view). One has to sprinkle double negatives (`if not args.no_blah`) throughout the code that uses the arg. You can, of course, "unwrap" this repeated inversion by creating a local variable that stores the inverted value, but this somewhat obscures the fact that the value is derived from an `argparse` argument (while `args.blah`) is more explicit and self-documenting.

Given there is a pretty reasonable work-around I think this is a low-priority feature ask, but personally I would use it if it became available just because I prefer to keep this sort of flag inversion in the CLI parsing and out of the business logic

If you did think the idea was reasonable I'd be willing to take a stab at an implementation. Basically I'm thinking something like an optional switch in the `arg()` function to invert the default for a bool switch. (That's a very uneducated guess at how to implement it, though, from a quick scan of the codebase.)

Hopefully I'm not overlooking an easy way to what I'm looking for already, but if I am, please set me straight!

**Comment by bluenote10** [comment]
Yes I thought about that as well, should be easy to add I would assume. For now it should already be possible to achieve that by using the renaming feature, i.e., it is possible to just manually specify a name that does the negation:

```py
import typed_argparse as tap


class Args(tap.TypedArgs):
    blah: bool = tap.arg("--no-blah", default=True)


def run(args: Args):
    print(args)


if __name__ == "__main__":
    tap.Parser(Args).bind(run).run()
```

Would result in:

```
$ python /tmp/test.py -h
usage: test.py [-h] [--blah]

options:
  -h, --help  show this help message and exit
  --blah

$ python /tmp/test.py
Args(blah=True)

$ python /tmp/test.py --no-blah
Args(blah=False)
```

**Comment by ptous** [comment]
> For now it should already be possible to achieve that by using the renaming feature, i.e., it is possible to just manually specify a name that does the negation:
> 
> ```python
> import typed_argparse as tap
> 
> class Args(tap.TypedArgs):
>     blah: bool = tap.arg("--no-blah", default=True)

🤦 See, this right here is why always try to include a "please tell me if I'm missing something obvious" in issues like this.

So the library really already does what I want, if in a bit of a surprising way. I missed [this](https://github.com/typed-argparse/typed-argparse/blob/master/typed_argparse/parser.py#L485):

```
    if annotation.is_bool:
        if arg.has_default():
            default_value = arg.resolve_default()
            if default_value is True:
                kwargs["action"] = "store_false"
            elif default_value is False:
                kwargs["action"] = "store_true"
            else:
```

I did try to look for boolean inversion behavior in the docs. Unless I'm missing it badly (clearly possible) I don't think this behavior is called out. If I'm right about that, calling it out explicitly is probably worthwhile.
