### ISSUE TITLE
Default sub command

### ISSUE THREAD

**Issue by Roang-zero1** [typed-argparse/typed-argparse#44]
I am currently writing a cli/gui hybrid application with the use of sub commands.
Is there a way to implement sub-parsers in a way that marks one of them as default?

I am currently just adding the subcommand to the args via:
```python
args = argv
    if len(args) == 1:
        args.append("gui")
    Parser(...).bind(...).run(args[:1]
```
But I would realy not add this to potential default sub - sub commands..

**Comment by bluenote10** [comment]
That's a good question. Intuitively I feel that sub-parsers with a default may not have sound semantics in general. Imagine `some_command` has two sub-commands / sub-parsers `foo` and `bar`. Now assume that the `foo` subparser takes one mandatory positional argument, and we make it the default sub-parser. This will result in an ambiguity that cannot be handled in general:

```sh
# regular call of subparser foo with positional
some_command foo some_positional_arg

# calling bar
some_command bar

# calling foo via default
some_command some_positional_arg

# but what is this -- is it the positional arg of foo or is it an attempt to call the other sub parser?
some_command bar
```

Have you tried if plain `argparse` can do something like that? I'd assume it errors when things get ambiguous.
