### ISSUE TITLE
Feature request: use docstring as help string

### ISSUE THREAD

**Issue by pdc1** [typed-argparse/typed-argparse#51]
Hello again!

VS Code has the ability to use a `"""` string under an attribute as the documentation for the field. I am wondering if it would be possible for TypedArgs to use such strings as a default `help=` value?

For example, I can define documentation for an args field like so:

```python
class Args(tap.TypedArgs):
    debug: bool = tap.arg(
        "-d", default=False, help="Output additional debugging messages.")
    """Output additional debugging messages."""
```

And then a mouse-over in VS Code looks like this:

![image](https://github.com/typed-argparse/typed-argparse/assets/1159702/6a40e8c1-8fe2-49c5-9480-bda6b353f816)

It would be great to be able to use the "docstring" as the help string, e.g. like this:

```python
class Args(tap.TypedArgs):
    debug: bool = tap.arg("-d", default=False)
    """Output additional debugging messages."""
```
Thanks!

**Comment by bluenote10** [comment]
I just did a quick check, but it doesn't look like that docstring information is available at runtime, or is it?

**Comment by pdc1** [comment]
I am not very knowledgeable about python internals, but perhaps something like this could work? https://stackoverflow.com/a/31764368

**Comment by bluenote10** [comment]
If Python would support it officially and it would just be readable from `__doc__` this would be doable. But having to re-parse the source file this is originating from an guessing where it was in the AST is probably too fragile and slow. In particular it would be super ugly to support inheritance properly.

Perhaps `typing.Annotated` would be an alternative?

**Comment by pdc1** [comment]
I took a look at `typing.Annotated` but it is a very generic mechanism and there aren't any good conventions for using it as an attribute docstring.

Since there is no official support for variable docstring, and no good runtime workaround, I will close this request. Thanks for the clarifications!
